POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "John",
    "email": "john@gmail.com",
    "password": "123456789"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "john@gmail.com",
    "password": "123456789"
}

###

GET http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE0OGI4YjliMWY2M2E3NjYxZjc3NDUiLCJ1c2VybmFtZSI6IkJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJDN3SkpNQ1RTZk9vRURXckVySFRmNmV4WWdod25IUEFqQVNLWTB0OW44dDQ5YncyNWhwZmo2IiwiY3JlYXRlZFNlcnZlcnMiOltdLCJqb2luZWRTZXJ2ZXJzIjpbXSwicHJvZmlsZVBpYyI6IiIsImNyZWF0ZWRBdCI6IjIwMjItMDktMDRUMTE6Mjc6MDcuMDE3WiIsInVwZGF0ZWRBdCI6IjIwMjItMDktMDRUMTE6Mjc6MDcuMDE3WiIsIl9fdiI6MCwiaWF0IjoxNjYyMjkwODQzfQ.XILNdzr70FKPOYJmgo3_dVJ-33Gj5GZgz3s5eUmySJs"
}

###

POST http://localhost:5000/api/servers/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE0OGI4YjliMWY2M2E3NjYxZjc3NDUiLCJ1c2VybmFtZSI6IkJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImNyZWF0ZWRTZXJ2ZXJzIjpbXSwiam9pbmVkU2VydmVycyI6W10sImlhdCI6MTY2MjI5Njc0OCwiZXhwIjoxNjYyMjk4NTQ4fQ.0PLOYlrXT0CFfznpSFwDpQOmmIi4CHfW8Iua4i9CFEI

{
    "title": "First server",
    "description": "This is a description of 'first server'!"
}

###

PUT http://localhost:5000/api/servers/update/6314a64ba8d4e9101689802a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MzE0OGI4YjliMWY2M2E3NjYxZjc3NDUiLCJ1c2VybmFtZSI6IkJvYiIsImVtYWlsIjoiYm9iQGdtYWlsLmNvbSIsImNyZWF0ZWRTZXJ2ZXJzIjpbXSwiam9pbmVkU2VydmVycyI6W10sImlhdCI6MTY2MjMwMDA0OSwiZXhwIjoxNjYyMzAxODQ5fQ.Ryb23HTWObvCQbTsyv7fwebXE71sV9IDXB7BbLI1IwU

{
    "title": "WHATS UP MY NIGGAS"
}
